Myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import Home_view
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
    path('', Home_view,name='home'),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path,include
from django.conf.urls import url
from .views import *

app_name='accounts'

urlpatterns = [


    path('login/',login_view,name='login'),
    path('register/',register_view,name='register'),
    path('logout/',logout_view,name='logout'),


]

post/urls.py
from django.urls import path,include
from django.conf.urls import url
from .views import *

app_name='post'

urlpatterns = [

    path('',post_index,name='index'),
    path('index/',post_index,name='index'),
    path('create/',post_create,name='create'),
    path('<slug:slug>/',post_detail,name='detail'),
    path('<slug:slug>/update/',post_update,name='update'),
    path('<slug:slug>/delete/',post_delete,name='delete'),
    # url(r'^index/$', post_index, name="index"),
    #
    # url(r'^create/$', post_create, name='create'),
    #
    # url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    #
    # url(r'^(?P<slug>[\w-]+)/update/$', post_update, name="update"),
    #
    # url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),


]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse


# Create your views here.
def Home_view(request):
    if request.user.is_authenticated:

        context = {
            'isim': 'Yavuz Bektaş'

        }
    else:
        context = {
            'isim': 'Kullanıcı Tanımlı değil'

        }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport"  content="width=device-width initial-scale=1">
    <title>{% block title %} Kişisel Web Sayfam{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
        {% include 'header.html' %}
        {% include 'messages.html' %}
        {% block body %}




        {% endblock %}
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">Django Dersleri</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">

                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}">Yazı Ekle</a></li>
                {% endif %}


                <li><a href="{% url 'post:index' %}">Blog</a></li>
                <li><a href="#">Hakkımda</a></li>
                <li><a href="#">İletişim</a></li>
                {% if not request.user.is_authenticated %}
                <li><a href="{% url 'accounts:register' %}">Üye Ol</a></li>
                <li><a href="{% url 'accounts:login' %}">Giriş Yap</a></li>
                 {% else %}
                  <li><a href="{% url 'accounts:logout' %}">Çıkış Yap</a></li>
                {% endif %}
            </ul>


        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}


merhaba burası ana sayfa sayın {{ isim }}

{% block body %}
{#        <div class="container-fluid">#}
{#            <div class="row">#}
{#                <div class="col-md-3 col-sm-6 "  style="background-color: #ebfb30; height:100px;">1.urun</div>#}
{#                <div class="col-md-3 col-sm-6 " style="background-color: #fb3b39; height:100px;">2.urun</div>#}
{#                <div class="col-md-3 col-sm-6 " style="background-color: #51c2fb; height:100px;">3.urun</div>#}
{#                <div class="col-md-3 col-sm-6 " style="background-color: #44fb6a; height:100px;">4.urun</div>#}
{#            </div>#}
{##}
{#        </div>#}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4"  style="background-color: #ebfb30; height:100px;">1.urun</div>
            <div class="col-md-8"  style="background-color: #1ffbe2; height:100px;">
                <div class="col-md-4"  style="background-color: #4fecfb; height:100px;">2.urun</div>
                <div class="col-md-4"  style="background-color: #fb6166; height:100px;">3.urun</div>
                <div class="col-md-4"  style="background-color: #84fb7e; height:100px;">4.urun</div>
                </div>
            Hos geldiniz, {{ request.user.get_full_name }}
        </div>
    </div>
{% endblock %}

templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ message }}
        </div>
    {% endfor %}
</ul>
{% endif %}